### ISSUE TITLE
Minify inline has to be first 

### ISSUE THREAD

**Issue by vitor-ao** [doublethreedigital/minify#9] opened 2020-10-17 20:03 UTC
If i use both `{{ minify:js}}` and `{{ minify:js src="/test.js"}}`, the inline minify has to be first for the page to be generated correctly. If it is after, the first is generated as `<script src="http://barato-ao.test/storage/_minify/test.js?version=96ada47e1eb6e7f6ad56ed328dc6af595fb8922174938a85a80eb13790d3adba` (doesn't close and the second one is not generated).

Happens on both tags (`{{ minify:js}}` and `{{ minify:css}}`)

## minify before inline
<img src="https://lh6.googleusercontent.com/CAkaYGS_8x9xQihAp1n0luVpFtfqFR0fPg6vCBYwP9U5mAFWMswWCKuX2dxHzBINpnpoXvC4x9H70Q=w1920-h668-rw" />

## minify after inline 
<img src="https://lh6.googleusercontent.com/lGtRHJKhgC6jsd3EyxZ0JpVszHTfZM11YLt80AgsPpo0SU0IOhm_clvvWUusCysIX7r5tLxOljecQw=w1920-h937-rw" />

## Steps to reproduce

1. Create a `{{minify:js src="/test.js"}}`
2. Create an inline script with `{{ minify:js}}`
3. Refresh to render the page

## Expected behaviour

Should generate both tags, in either order.

## Environment information

**Statamic version:** 3.0.19 Pro
_run `php please -V` to find it._

**PHP version:** 7.4.11
_run `php -v` to find it_

**Operating System:**
- [ ] MacOS
- [ ] Linux
- [x] Windows

**Browser:**
- [ ] Chrome
- [X] Firefox
- [ ] Safari

**Comment by damcclean** [comment] 2020-10-17 21:26
Thanks for reporting! I'll hopefully get time to look into it this week.

**Comment by damcclean** [comment] 2020-11-04 22:36
I've had a look into this issue. I think it's caused by the first `{{ minify:js }}` not being a tag pair but the second one being a tag pair. If you add a closing `{{ /minify:js }}` tag to the end of every minify tag use, it should hopefully resolve the problem.

I know this isn't a long term fix so I'll keep this issue open. I think it could be a bug in Statamic's parser.

**Comment by damcclean** [comment] 2020-12-21 22:53
I'm closing this issue now due to inactivity and the fact that it's not really a Minify related issue, more of a bug to do with the Antlers parser.

**Closed by damcclean** 2020-12-21 22:53 UTC
Labels: bug
